// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateGCloud() {
  return window['go']['main']['App']['AuthenticateGCloud']();
}

export function CheckGCloudAuth() {
  return window['go']['main']['App']['CheckGCloudAuth']();
}

export function GetActiveProject() {
  return window['go']['main']['App']['GetActiveProject']();
}

export function GetComputeInstances(arg1, arg2) {
  return window['go']['main']['App']['GetComputeInstances'](arg1, arg2);
}

export function GetGCPProjects() {
  return window['go']['main']['App']['GetGCPProjects']();
}

export function GetPortForwardStatus(arg1) {
  return window['go']['main']['App']['GetPortForwardStatus'](arg1);
}

export function GetZones(arg1) {
  return window['go']['main']['App']['GetZones'](arg1);
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function SetActiveProject(arg1) {
  return window['go']['main']['App']['SetActiveProject'](arg1);
}

export function StartPortForward(arg1) {
  return window['go']['main']['App']['StartPortForward'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
